### ISSUE TITLE
MIT license broken

### ISSUE THREAD

**Issue by fregante** [plasmo-corp/cwu#15]
Hello, this is a fork of my project at https://github.com/fregante/chrome-webstore-upload but the license was stripped and replaced. Please use the licensed code correctly. 

https://github.com/fregante/chrome-webstore-upload/blob/main/license

**Comment by louisgv** [comment]
Howdy @fregante - Apologize for my mistake! I forgot to fix the license as `cwu` was created from scratch and not forked `chrome-webstore-upload` via the GitHub fork tool, thus it uses the default MIT license in my typescript template xD. The other fork of your repo, which I studied for `cwu` is over [here](https://github.com/plasmo-foss/chrome-webstore-upload-esm/blob/main/license), which should have the right license.

For cwu, please check this PR and let me know if I missed anything: #16 

Thanks for creating https://github.com/fregante/chrome-webstore-upload👍

**Comment by fregante** [comment]
> Thanks for creating [https://github.com/fregante/chrome-webstore-upload👍](https://github.com/fregante/chrome-webstore-upload%F0%9F%91%8D)

I only maintain it 👍 ☺️ 

https://github.com/fregante/chrome-webstore-upload/commit/58bfb896f59bc4ee4fa2b6901d5fc72b7a25532e
